/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer */

#ifndef _Included_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
#define _Included_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    append
 * Signature: ([[Lru/kfu/itis/issst/crfsuite4j/Attribute;[Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_append
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    params
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_params
  (JNIEnv *, jobject);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    set
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_set
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    help
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_help
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_init
  (JNIEnv *, jobject);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    doSelect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_doSelect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer
 * Method:    doTrain
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ru_kfu_itis_issst_crfsuite4j_CrfSuiteTrainer_doTrain
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
